import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  index,
  integer,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { clients } from "./clients";
import { galleries } from "./galleries";
import { shoots } from "./shoots";

// SCL-506/507 (PRD §6.5 "Upsells do MVP de lançamento"): catalog of post-shoot
// products, per-Gallery offers and the orders a client requests from her
// Gallery. Staff-only through the Data API (migration 0052); the client portal
// reads and writes through server-side domain code only. Money follows the rest
// of the schema: numeric(10,2) decimal strings, never floats (lib/money.ts).

// Product kinds are data the Admin picks per product, not a UI catalog: the
// products themselves (names, prices, descriptions) live in upsell_products.
export const upsellProductKindValues = [
  "foto_adicional",
  "colecao_completa",
  "album",
  "quadro",
  "reel_stories",
  "outro",
] as const;

// Order lifecycle, separate from payment: whether the order was paid is derived
// from the Payment rows linked to it (payments.upsell_order_id).
export const upsellOrderStatusValues = ["solicitado", "confirmado", "em_producao", "entregue", "cancelado"] as const;

export type UpsellProductKind = (typeof upsellProductKindValues)[number];
export type UpsellOrderStatus = (typeof upsellOrderStatusValues)[number];

export const upsellOrderStatusEnum = pgEnum("upsell_order_status", upsellOrderStatusValues);

export const upsellProducts = pgTable(
  "upsell_products",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    kind: text("kind", { enum: upsellProductKindValues }).notNull(),
    name: text("name").notNull(),
    // Shown to the client in her Gallery.
    description: text("description"),
    // Staff-only (supplier, production notes); never serialized to the portal.
    internalNotes: text("internal_notes"),
    price: numeric("price", { precision: 10, scale: 2 }).notNull(),
    active: boolean("active").notNull().default(true),
    sortOrder: integer("sort_order").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    unique("upsell_products_name_unique").on(table.name),
    check(
      "upsell_products_kind_valid",
      sql`${table.kind} in ('foto_adicional', 'colecao_completa', 'album', 'quadro', 'reel_stories', 'outro')`,
    ),
    check("upsell_products_price_non_negative", sql`${table.price} >= 0`),
  ],
);

// Which products a Gallery offers. A Gallery belongs to exactly one Shoot
// (galleries_shoot_id_unique), so this is also the per-Shoot offer.
export const galleryUpsellOffers = pgTable(
  "gallery_upsell_offers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    galleryId: uuid("gallery_id")
      .notNull()
      .references(() => galleries.id, { onDelete: "cascade" }),
    productId: uuid("product_id")
      .notNull()
      .references(() => upsellProducts.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    unique("gallery_upsell_offers_gallery_product_unique").on(table.galleryId, table.productId),
    index("gallery_upsell_offers_product_idx").on(table.productId),
  ],
);

export const upsellOrders = pgTable(
  "upsell_orders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Financial records: never cascade-deleted (same as payments → shoots).
    clientId: uuid("client_id")
      .notNull()
      .references(() => clients.id),
    shootId: uuid("shoot_id")
      .notNull()
      .references(() => shoots.id),
    galleryId: uuid("gallery_id")
      .notNull()
      .references(() => galleries.id),
    status: upsellOrderStatusEnum("status").notNull().default("solicitado"),
    // Snapshot: sum of the items' line totals at request time.
    total: numeric("total", { precision: 10, scale: 2 }).notNull(),
    clientNotes: text("client_notes"),
    // Idempotency key generated by the portal form: a repeated submit returns
    // the same order instead of creating a second one.
    requestKey: uuid("request_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    unique("upsell_orders_client_request_key_unique").on(table.clientId, table.requestKey),
    // Target of payments_upsell_order_fk: a payment's order is on the payment's Shoot.
    unique("upsell_orders_id_shoot_unique").on(table.id, table.shootId),
    check("upsell_orders_total_non_negative", sql`${table.total} >= 0`),
    index("upsell_orders_shoot_idx").on(table.shootId),
    index("upsell_orders_status_created_idx").on(table.status, table.createdAt),
  ],
);

export const upsellOrderItems = pgTable(
  "upsell_order_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => upsellOrders.id, { onDelete: "cascade" }),
    // The catalog row may later change or be deleted; kind/name/description/price
    // below are the snapshot the client agreed to.
    productId: uuid("product_id").references(() => upsellProducts.id, { onDelete: "set null" }),
    kind: text("kind", { enum: upsellProductKindValues }).notNull(),
    name: text("name").notNull(),
    description: text("description"),
    unitPrice: numeric("unit_price", { precision: 10, scale: 2 }).notNull(),
    quantity: integer("quantity").notNull(),
    lineTotal: numeric("line_total", { precision: 10, scale: 2 }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    unique("upsell_order_items_order_product_unique").on(table.orderId, table.productId),
    check(
      "upsell_order_items_kind_valid",
      sql`${table.kind} in ('foto_adicional', 'colecao_completa', 'album', 'quadro', 'reel_stories', 'outro')`,
    ),
    check("upsell_order_items_unit_price_non_negative", sql`${table.unitPrice} >= 0`),
    check("upsell_order_items_quantity_positive", sql`${table.quantity} > 0`),
    check(
      "upsell_order_items_line_total_consistent",
      sql`${table.lineTotal} = ${table.unitPrice} * ${table.quantity}`,
    ),
  ],
);

export type UpsellProduct = typeof upsellProducts.$inferSelect;
export type NewUpsellProduct = typeof upsellProducts.$inferInsert;
export type GalleryUpsellOffer = typeof galleryUpsellOffers.$inferSelect;
export type UpsellOrder = typeof upsellOrders.$inferSelect;
export type NewUpsellOrder = typeof upsellOrders.$inferInsert;
export type UpsellOrderItem = typeof upsellOrderItems.$inferSelect;
export type NewUpsellOrderItem = typeof upsellOrderItems.$inferInsert;
